server:
  port: 8443
#  ssl:
#    key-store: classpath:keystore.jks
#    key-store-password: kurento
#    key-store-type: JKS
#    key-alias: kurento-selfsigned


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://j4b106.p.ssafy.io/b106?useUnicode=true&charaterEncoding=utf-8
    username: root
    password: j4B106_dogcat
  main:
    allow-bean-definition-overriding: true

