pipeline {
    agent any
    tools {
        gradle "gradle6.8.3"
    }
    stages {
        stage('Build') {
            steps {
                script {
                    try { 
                        mattermostSend (
                            color: "#2A42EE", 
                            message: "Build STARTED: ${env.JOB_NAME} #${env.BUILD_NUMBER} (<${env.BUILD_URL}|Link to build>)"
                        ) 
                        sh 'docker-compose build'
                    } catch(e) {
                        currentBuild.result = "FAILURE"
                    } finally {
                        if(currentBuild.result != "FAILURE") {
                            mattermostSend (
                                color: "good", 
                                message: "Build SUCCESS: ${env.JOB_NAME} #${env.BUILD_NUMBER} (<${env.BUILD_URL}|Link to build>)"
                            )
                        } else {
                            mattermostSend (
                                color: "danger", 
                                message: "Build FAILED: ${env.JOB_NAME} #${env.BUILD_NUMBER} (<${env.BUILD_URL}|Link to build>)"
                            )
                        }
                    }
                }
            }
        }
        stage('Signaling Build') {
            steps {
                // sh 'cd signaling'
                // sh 'gradle bootRun --stacktrace'
                sh 'cd signaling'
                sh 'pwd'
                sh 'ls -la'
            }
        }
        stage('Deploy') {
            steps {
                sh 'docker-compose up -d'
            }
        }
    }
}