server:
  servlet:
    context-path: /api
  error:
    include-message: always

spring:
  # DB 접속
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://j4b106.p.ssafy.io/b106?useUnicode=true&charaterEncoding=utf-8
#    username: root
#    password: j4B106_dogcat
    url: jdbc:mysql://spring-study.cfhtw7hbyeyq.ap-northeast-2.rds.amazonaws.com:3306/b106?useUnicode=true&charaterEncoding=utf-8
    username: melon
    password: ssafymelon


  # JPA 설정
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # 메일 전송
  mail:
    host: smtp.gmail.com
    port: 587
    username: ekdbs628@gmail.com
    password: MacBye^^
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
#  jackson:
#    deserialization: true

logging:
  level:
    org:
    springframwork:
      security: debug

# 테스트 계정 아이디, 비밀번호
my-app:
  admin-email: admin@ssafy.com
  admin-password: ssafy
  client-id: ssafy
  client-secret: ssafy
  server-url: https://j4b106.p.ssafy.io
